name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: dimasyoga42/metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          filename: metrics.repository.svg
          user: dimasyoga42
          repo: metrics
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: dimasyoga42/metrics/projects/1
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta